=== FilipGrela/Projekt-WAI-HIH/dev/src/web/xml/definition/definition.dtd
<!ENTITY % content-elements "(skladnik+ | zdjecie | opis | krok+)">
<!ENTITY % difficulty "(proste | srednie | trudne | 1 | 2 | 3)">


<!ELEMENT website (autor, page-title, zdjecie, potrawy, wiecej-link, spis-tresci, tabele)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT page-title (title, summary)>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title
        bold (true | false) #IMPLIED>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT zdjecie EMPTY>

<!NOTATION jpeg PUBLIC "image/jpeg">
<!NOTATION webp PUBLIC "image/webp">
<!NOTATION png PUBLIC "image/png">
<!ATTLIST zdjecie
        text CDATA #IMPLIED
        src CDATA #REQUIRED
        typ NOTATION (jpeg | webp | png) #REQUIRED>
<!ELEMENT potrawy (potrawa+)>
<!ATTLIST potrawy
        liczbaPotraw CDATA #IMPLIED>
<!ELEMENT potrawa (%content-elements;)>
<!ATTLIST potrawa
        data-dodania CDATA #IMPLIED
        nazwa CDATA #IMPLIED
        typ CDATA #IMPLIED
        trudnosc-przygotowania (%difficulty;) #IMPLIED>
<!ELEMENT skladnik (#PCDATA)>
<!ATTLIST skladnik
        ilosc CDATA #IMPLIED
        jednostka CDATA #IMPLIED>
<!ELEMENT krok (#PCDATA)>
<!ELEMENT opis (#PCDATA)>
<!ELEMENT wiecej-link (tytul, content)>
<!ELEMENT tytul (#PCDATA)>
<!ELEMENT content (przepisy-link)>
<!ATTLIST content
        text CDATA #IMPLIED>
<!ELEMENT przepisy-link (#PCDATA)>
<!ATTLIST przepisy-link
        href CDATA #IMPLIED>
<!ELEMENT spis-tresci (#PCDATA)>
<!ELEMENT tabele (head, row+)>
<!ELEMENT head (line+)>
<!ELEMENT row (line+)>
<!ELEMENT line (#PCDATA)>

=== FilipGrela/Projekt-WAI-HIH/dev/src/web/xml/definition/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE website SYSTEM "definition.dtd">
<website>
    <autor>Filip Grela</autor>
    <page-title>
        <title bold="true">Pasje, które otwierają świat!</title>
        <summary>O podróżach, górach i narciarstwie – moim oknem na Europę.</summary>
    </page-title>
    <zdjecie src="/img/food/potrawy.webp" typ="image/webp" text="Potrawy"/>
    <potrawy liczbaPotraw="3">
        <potrawa data-dodania="2024-10-28" trudnosc-przygotowania="proste" nazwa="Grillowany oscypek z żurawiną" typ="Ser">
            <skladnik ilosc="1" jednostka="szt.">Oscypek</skladnik>
            <skladnik ilosc="1" jednostka="łyżeczka">Oliwa z oliwek</skladnik>
            <skladnik ilosc="1" jednostka="łyżeczka">Żurawina</skladnik>
            <skladnik ilosc="1" jednostka="szczypta">Tymianek</skladnik>

            <zdjecie src="/img/food/oscypek.webp" typ="image/webp" text="Oscypek"/>

            <krok>Rozgrzej grill – oscypek najlepiej grillować na grillu węglowym lub elektrycznym, ale można także użyć patelni grillowej.</krok>
            <krok>Grillowanie – posmaruj oscypki delikatnie oliwą z oliwek (opcjonalnie) i grilluj z obu stron przez około 2-3 minuty, aż ser delikatnie się roztopi i zyska złoty kolor.</krok>
            <krok>Podawanie – wyjmij oscypki z grilla i podaj na talerzu, a następnie dodaj na wierzch łyżkę żurawiny.</krok>
            <krok>Dekoracja – dla urozmaicenia smaku można dodać świeże zioła, takie jak tymianek, które podkreślą smak sera.</krok>

            <opis>To szybkie i smakowite danie idealnie nadaje się jako przystawka lub lekka przekąska, zwłaszcza podczas zimowych dni w górach.</opis>
        </potrawa>

        <potrawa trudnosc-przygotowania="proste" nazwa="Placki po zbójnicku" typ="Danie główne">

            <skladnik ilosc="500" jednostka="g">Ziemniaki</skladnik>
            <skladnik ilosc="1" jednostka="szt.">Cebula</skladnik>
            <skladnik ilosc="2" jednostka="szt.">Jajka</skladnik>
            <skladnik ilosc="100" jednostka="g">Mąka</skladnik>
            <skladnik ilosc="200" jednostka="g">Wołowina</skladnik>
            <skladnik ilosc="1" jednostka="szczypta">Sól, pieprz, czosnek</skladnik>
            <skladnik ilosc="5" jednostka="ml">Olej do smażenia</skladnik>

            <zdjecie src="/img/food/placki-po-zbojnicku.webp" typ="we" text="Placki po zbójnicku"/>

            <krok>Przygotowanie ziemniaków – obierz ziemniaki i zetrzyj je na tarce o grubych oczkach. Odsącz nadmiar wody.</krok>
            <krok>Dodanie składników – do ziemniaków dodaj mąkę, jajka, sól i pieprz. Dokładnie wymieszaj.</krok>
            <krok>Smażenie – na rozgrzanym oleju smaż placki z obu stron, aż będą złociste.</krok>
            <krok>Sos zbójnicki – wołowinę podsmaż z cebulą i czosnkiem, dopraw solą, pieprzem i papryką.</krok>
            <krok>Podawanie – placki podawaj z mięsem i sosem. Możesz udekorować natką pietruszki.</krok>

            <opis>Placki po zbójnicku to klasyczne danie kuchni góralskiej, doskonałe na sycący obiad.</opis>
        </potrawa>

        <potrawa trudnosc-przygotowania="trudne" nazwa="Kwaśnica" typ="Zupa">
            <skladnik ilosc="1" jednostka="kg">Kapusta kiszona</skladnik>
            <skladnik ilosc="500" jednostka="g">Wędzone żeberka</skladnik>
            <skladnik ilosc="300" jednostka="g">Surowy boczek</skladnik>
            <skladnik ilosc="2" jednostka="l">Woda</skladnik>
            <skladnik ilosc="3" jednostka="szt.">Ziemniaki</skladnik>
            <skladnik ilosc="2" jednostka="szt.">Marchewki</skladnik>
            <skladnik ilosc="1" jednostka="szt.">Cebula</skladnik>
            <skladnik ilosc="2" jednostka="szt.">Liście laurowe</skladnik>
            <skladnik ilosc="3" jednostka="szt.">Ziarna ziela angielskiego</skladnik>
            <skladnik ilosc="1" jednostka="szczypta">Sól i pieprz</skladnik>

            <zdjecie src="/img/food/kwasnica.webp" typ="image/webp" text="Kwaśnica"/>

            <krok>Gotowanie mięsa – w dużym garnku zagotuj wodę, dodaj wędzone żeberka, boczek, liście laurowe i ziele angielskie. Gotuj na wolnym ogniu przez około godzinę, aż mięso będzie miękkie.</krok>
            <krok>Dodanie kapusty – po godzinie dodaj do garnka kiszoną kapustę (jeśli jest bardzo kwaśna, można ją wcześniej przepłukać). Gotuj wszystko razem przez kolejne 30 minut.</krok>
            <krok>Warzywa – obierz i pokrój ziemniaki oraz marchewki na kawałki. Cebulę drobno posiekaj. Dodaj do zupy i gotuj, aż ziemniaki będą miękkie.</krok>
            <krok>Przyprawienie – dopraw kwaśnicę solą i pieprzem wedle uznania.</krok>
            <krok>Podawanie – podawaj gorącą kwaśnicę z kawałkami mięsa i ziemniakami. Można dodać także chleb razowy jako dodatek.</krok>

            <opis>Kwaśnica to tradycyjna góralska zupa na bazie kiszonej kapusty i wędzonego mięsa, idealna na zimowe dni.</opis>
        </potrawa>
    </potrawy>
    <wiecej-link>
        <tytul>Chcesz więcej przepisów?</tytul>
        <content text="Znajdzesz je klikajc ">
            <przepisy-link href="https://www.przepisy.pl/">TUTAJ</przepisy-link>
        </content>
    </wiecej-link>

    <spis-tresci>
        Tatry Alpy Włochy
    </spis-tresci>

    <tabele>
        <head>
            <line>Kierunek</line>
            <line>Popularne Potrawy</line>
            <line>Lokalizacja</line>
        </head>
        <row>
            <line>Gruzja</line>
            <line>Chinkali, Chaczapuri</line>
            <line>Kaukaz, Wschodnia Europa</line>
        </row>
        <row>
            <line>Portugalia</line>
            <line>Bacalhau, Pastel de Nata</line>
            <line>Południowa Europa</line>
        </row>
        <row>
            <line>Maroko</line>
            <line>Kuskus, Tajine</line>
            <line>Północna Afryka</line>
        </row>
        <row>
            <line>Japonia</line>
            <line>Sushi, Ramen</line>
            <line>Azja Wschodnia</line>
        </row>
        <row>
            <line>Meksyk</line>
            <line>Tacos, Guacamole</line>
            <line>Ameryka Północna</line>
        </row>
    </tabele>
</website>
